/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-06-30 17:23:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.client;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class security_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Di/Desktop/LTWeb/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/do-an-java/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098685890000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1656093238021L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  <!-- Start header section -->\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./header/mainHeader.jsp", out, true);
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <section id=\"aa-catg-head-banner\">\r\n");
      out.write("   <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/view/client/assets/images/banner_tc.jpg\" alt=\"banner sản phẩm\">\r\n");
      out.write("   <div class=\"aa-catg-head-banner-area\">\r\n");
      out.write("     <div class=\"container\">\r\n");
      out.write("      <div class=\"aa-catg-head-banner-content\">\r\n");
      out.write("        <h2>Chính sách bảo mật</h2>\r\n");
      out.write("        <ol class=\"breadcrumb\">\r\n");
      out.write("          <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">Trang chủ</a></li>\r\n");
      out.write("          <li style=\"color:#fff\">Chính sách</li>         \r\n");
      out.write("        </ol>\r\n");
      out.write("      </div>\r\n");
      out.write("     </div>\r\n");
      out.write("   </div>\r\n");
      out.write("  </section>\r\n");
      out.write("  <section id=\"aa-product-category\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("      	<div>\r\n");
      out.write("      		<h1 style =\"text-align: center; color: red;\">Chính Sách Bảo Mật</h1>\r\n");
      out.write("      		<strong>Cám ơn quý khách đã truy cập vào website Nông Sản 24h</strong><br><br>\r\n");
      out.write("      		<p>Chúng tôi tôn trọng và cam kết sẽ bảo mật những thông tin mang tính riêng tư của bạn. \r\n");
      out.write("      		Xin vui lòng đọc bản Chính sách bảo mật dưới đây để hiểu hơn những cam kết mà chúng tôi thực \r\n");
      out.write("      		hiện nhằm tôn trọng và bảo vệ quyền lợi của người truy cập.</p>\r\n");
      out.write("      		<p>Chính sách bảo mật sẽ giải thích cách chúng tôi tiếp nhận, sử dụng và (trong trường hợp nào đó) \r\n");
      out.write("      		tiết lộ thông tin cá nhân của bạn. Chính sách cũng sẽ giải thích các bước chúng tôi thực hiện để bảo \r\n");
      out.write("      		mật thông tin cá nhân của khách hàng. Cuối cùng, Chính sách bảo mật sẽ giải thích quyền lựa chọn của quý \r\n");
      out.write("      		khách về việc thu thập, sử dụng và tiết lộ thông tin cá nhân của mình.</p>\r\n");
      out.write("      		<p>Bảo vệ dữ liệu cá nhân và gây dựng được niềm tin cho quý khách là vấn đề rất quan trọng với chúng tôi. \r\n");
      out.write("      		Vì vậy, chúng tôi sẽ dùng tên và các thông tin khác liên quan đến quý khách tuân thủ theo nội dung của Chính \r\n");
      out.write("      		sách bảo mật. Chúng tôi chỉ thu thập những thông tin cần thiết liên quan đến giao dịch mua bán.</p>\r\n");
      out.write("      		<p>Chúng tôi sẽ giữ thông tin của khách hàng trong thời gian luật pháp quy định hoặc cho mục đích nào đó. \r\n");
      out.write("      		Quý khách có thể truy cập vào website và trình duyệt mà không cần phải cung cấp chi tiết cá nhân. Lúc đó, \r\n");
      out.write("      		bạn đang ẩn danh và chúng tôi không thể biết bạn là ai nếu bạn không đăng nhập vào tài khoản của mình.</p>\r\n");
      out.write("      		<strong>1. Thu thập thông tin cá nhân</strong>\r\n");
      out.write("      		<p>\r\n");
      out.write("      		Chúng tôi sẽ thu thập nhiều thông tin khác nhau của quý khách khi bạn muốn đặt hàng trên website thegioinongsan.net<br><br>\r\n");
      out.write("      		\r\n");
      out.write("			Chúng tôi thu thập, lưu trữ và xử lý thông tin của bạn cho quá trình mua hàng và cho những thông báo sau này, và để cung cấp dịch vụ. \r\n");
      out.write("			Chúng tôi không giới hạn thông tin cá nhân: danh hiệu, tên, giới tính, ngày sinh, email, địa chỉ, địa chỉ giao hàng, số điện thoại, fax, \r\n");
      out.write("			chi tiết thanh toán, chi tiết thanh toán bằng thẻ hoặc chi tiết tài khoản ngân hàng.<br><br>\r\n");
      out.write("			\r\n");
      out.write("			Chúng tôi sẽ dùng thông tin quý khách đã cung cấp để xử lý đơn đặt hàng, cung cấp các dịch vụ và thông tin yêu cầu thông qua website và \r\n");
      out.write("			theo yêu cầu của bạn. Hơn nữa, chúng tôi sẽ sử dụng các thông tin đó để quản lý tài khoản của bạn; xác minh và thực hiện giao dịch trực \r\n");
      out.write("			tuyến, kiểm toán việc tải dữ liệu từ web; cải thiện bố cục và nội dung trang web và điều chỉnh cho phù hợp với người dùng; nhận diện khách vào web, \r\n");
      out.write("			nghiên cứu nhân khẩu học, gửi thông tin bao gồm thông tin sản phẩm và dịch vụ, nếu bạn không có dấu hiệu từ chối. Nếu quý khách không muốn nhận bất \r\n");
      out.write("			cứ thông tin tiếp thị của chúng tôi thì có thể từ chối bất cứ lúc nào.<br><br>\r\n");
      out.write("\r\n");
      out.write("			Chúng tôi có thể chuyển tên và địa chỉ cho bên thứ ba để họ giao hàng cho bạn (ví dụ cho bên chuyển phát nhanh hoặc nhà cung cấp).<br><br>\r\n");
      out.write("\r\n");
      out.write("			Các khoản thanh toán trực tuyến sẽ được xử lý bởi các cổng thanh toán đảm bảo và hệ thống ngân hàng. Quý khách chỉ đưa cho chúng tôi hoặc website những thông tin \r\n");
      out.write("			chính xác, không gây nhầm lẫn và phải thông báo cho chúng tôi nếu có thay đổi.<br><br>\r\n");
      out.write("\r\n");
      out.write("			Chi tiết đơn đặt hàng của bạn được chúng tôi lưu giữ nhưng vì lí do bảo mật nên chúng tôi không công khai trực tiếp được. Tuy nhiên, quý khách có thể tiếp cận thông \r\n");
      out.write("			tin bằng cách đăng nhập tài khoản trên web. Tại đây, bạn sẽ thấy chi tiết đơn đặt hàng của mình, những sản phẩm đã nhận và những sản phẩm đã gửi và chi tiết email, \r\n");
      out.write("			ngân hàng và bản tin mà bạn đặt theo dõi dài hạn. Quý khách cam kết bảo mật dữ liệu cá nhân và không được phép tiết lộ cho bên thứ ba. Chúng tôi không chịu bất kỳ trách \r\n");
      out.write("			nhiệm nào cho việc dùng sai mật khẩu nếu đây không phải lỗi của chúng tôi.\r\n");
      out.write("      		</p>\r\n");
      out.write("      		<strong><i>Điều lệ khác về thông tin cá nhân</i></strong>\r\n");
      out.write("      		<p>Chúng tôi có thể dùng thông tin cá nhân của bạn để nghiên cứu thị trường. Chi tiết sẽ được ẩn và chỉ được dùng để thống kê. Quý khách có thể từ chối không tham gia bất \r\n");
      out.write("      		cứ lúc nào. Bất kỳ câu trả lời cho khảo sát hoặc thăm dò dư luận mà chúng tôi cần bạn làm sẽ không được chuyển cho bên thứ ba. Việc cần thiết duy nhất là tiết lộ email của \r\n");
      out.write("      		bạn nếu bạn muốn tham gia. Câu trả lời sẽ được lưu tách riêng với email của bạn.<br><br>\r\n");
      out.write("\r\n");
      out.write("			Bạn sẽ nhận được thông tin về chúng tôi, về website, các website khác, sản phẩm, doanh số bán hàng, bản tin, bất cứ những gì liên quan đến các công ty nằm trong nhóm hoặc \r\n");
      out.write("			các đối tác kinh doanh. Nếu quý khách không muốn nhận những thông tin này, vui lòng nhấn vào link từ chối trong bất kỳ email chúng tôi gửi cho bạn. Trong vòng 7 ngày nhận \r\n");
      out.write("			chỉ dẫn của bạn, chúng tôi sẽ ngừng gửi thông tin. Nếu thấy không rõ, chúng tôi sẽ liên lạc với bạn.<br><br>\r\n");
      out.write("\r\n");
      out.write("			Chúng tôi sẽ tiếp tục giấu tên dữ liệu người dùng trên website và sử dụng cho nhiều mục đích khác nhau, bao gồm việc xác định vị trí của người dùng và cách sử dụng các khía \r\n");
      out.write("			cạnh nhất định của website hoặc đường link chứa trong email tới người dùng và cung cấp dữ liệu ẩn danh đó cho bên thứ 3 là nhà xuất bản. Tuy nhiên, dữ liệu này không có khả \r\n");
      out.write("			năng xác định cá nhân.</p>\r\n");
      out.write("			<strong>2. Sử dụng Cookie</strong>\r\n");
      out.write("			<p>\r\n");
      out.write("			Cookie là tập tin văn bản nhỏ có thể nhận dạng tên truy cập duy nhất từ máy tính của bạn đến máy chủ của chúng tôi khi bạn truy cập vào các trang nhất định trên website và \r\n");
      out.write("			sẽ được lưu bởi trình duyệt internet lên ổ cứng máy tính của bạn. Cookie được dùng để nhận dạng địa chỉ IP, lưu lại thời gian. Chúng tôi dùng cookie để tiện cho quý khách vào \r\n");
      out.write("			web (ví dụ: ghi nhớ tên truy cập khi bạn muốn vào thay đổi lại giỏ mua hàng mà không cần phải nhập lại địa chỉ email của mình) và không đòi hỏi bất kỳ thông tin nào về bạn \r\n");
      out.write("			(ví dụ: mục tiêu quảng cáo). Trình duyệt của bạn có thể được thiết lập không sử dụng cookie nhưng điều này sẽ hạn chế quyền sử dụng của bạn trên web. Xin vui lòng chấp nhận \r\n");
      out.write("			cam kết của chúng tôi là cookie không bao gồm bất cứ chi tiết cá nhân riêng tư nào và an toàn với virus. Muốn biết thêm về cookie, vui lòng truy cập web http://www.allaboutcookies.org \r\n");
      out.write("			hoặc để tìm hiểu cách loại bỏ cookie khỏi trình duyệt, vui lòng vào http://www.allaboutcookies.org/manage-cookies/index.html.<br><br>\r\n");
      out.write("\r\n");
      out.write("			Trình duyệt này sử dụng Google Analytics, một dịch vụ phân tích web được cung cấp bởi Google, Inc. (“Google”). Google Analytics dùng cookie, là những tập tin văn bản đặt trong máy tính \r\n");
      out.write("			để giúp website phân tích người dùng vào web như thế nào. Thông tin được tổng hợp từ cookie sẽ được truyền tới và lưu bởi Google trên các máy chủ tại Hoa Kỳ. Google sẽ dùng thông tin này \r\n");
      out.write("			để đánh giá cách dùng web của bạn, lập báo cáo về các hoạt động trên web cho các nhà khai thác web và cung cấp các dịch vụ khác liên quan đến các hoạt động internet và cách dùng internet. \r\n");
      out.write("			Google cũng có thể chuyển giao thông tin này cho bên thứ ba theo yêu cầu của pháp luật hoặc các bên thứ ba xử lý thông tin trên danh nghĩa của Google. Google sẽ không kết hợp địa chỉ IP \r\n");
      out.write("			của bạn với bất kỳ dữ liệu nào khác mà Google đang giữ. Quý khách có thể từ chối dùng cookie bằng cách chọn các thiết lập thích hợp trên trình duyệt của mình, tuy nhiên lưu ý rằng điều này \r\n");
      out.write("			sẽ ngăn bạn sử dụng triệt để chức năng của website. Bằng cách sử dụng trang web này, bạn đã đồng ý cho Google xử lý dữ liệu về bạn theo cách thức và các mục đích nêu trên.\r\n");
      out.write("			</p>\r\n");
      out.write("			<strong>3. Bảo mật</strong>\r\n");
      out.write("			<p>Chúng tôi có biện pháp thích hợp về kỹ thuật và an ninh để ngăn chặn truy cập trái phép hoặc trái pháp luật hoặc mất mát hoặc tiêu hủy hoặc thiệt hại cho thông tin của bạn. Khi thu thập \r\n");
      out.write("			dữ liệu trên web, chúng tôi thu thập chi tiết cá nhân của bạn trên máy chủ an toàn. Chúng tôi dùng tường lửa cho máy chủ. Khi thu thập chi tiết các thẻ thanh toán điện tử, chúng tôi dùng mã \r\n");
      out.write("			hóa bằng Secure Socket Layer (SSL). Khi chúng tôi không thể bảo đảm an ninh 100%, SSL sẽ gây khó khăn cho hacker muốn giải mã thông tin của quý khách. Bạn không nên gửi đầy đủ chi tiết của \r\n");
      out.write("			thẻ tín dụng hay thẻ ghi nợ khi chưa được mã hóa cho chúng tôi. Chúng tôi duy trì các biện pháp bảo vệ vật lý và điện tử trong mối liên kết với thu thập, lưu trữ và tiết lộ thông tin của bạn. \r\n");
      out.write("			Các thủ tục an toàn của chúng tôi nghĩa là chúng tôi có thể đôi khi yêu cầu giấy tờ chứng minh trước khi tiết lộ thông tin cá nhân cho bạn.<br><br>\r\n");
      out.write("\r\n");
      out.write("			Chúng tôi khuyên quý khách rằng quý khách không nên đưa thông tin chi tiết về việc thanh toán với bất kỳ ai bằng e-mail, chúng tôi không chịu trách nhiệm về những mất mát quý khách có thể gánh\r\n");
      out.write("			chịu trong việc trao đổi thông tin của quý khách qua internet hoặc email.<br><br>\r\n");
      out.write("\r\n");
      out.write("			Quý khách tuyệt đối không sử dụng bất kỳ chương trình, công cụ hay hình thức nào khác để can thiệp vào hệ thống hay làm thay đổi cấu trúc dữ liệu. Nghiêm cấm việc phát tán, truyền bá hay cổ vũ \r\n");
      out.write("			cho bất kỳ hoạt động nào nhằm can thiệp, phá hoại hay xâm nhập vào dữ liệu của hệ thống website. Mọi vi phạm sẽ bị tước bỏ mọi quyền lợi cũng như sẽ bị truy tố trước pháp luật nếu cần thiết.<br><br>\r\n");
      out.write("\r\n");
      out.write("			Mọi thông tin giao dịch sẽ được bảo mật nhưng trong trường hợp cơ quan pháp luật yêu cầu, chúng tôi sẽ buộc phải cung cấp những thông tin này cho các cơ quan pháp luật.<br><br>\r\n");
      out.write("\r\n");
      out.write("			Các điều kiện, điều khoản và nội dung của trang web này được điều chỉnh bởi luật pháp Việt Nam và tòa án Việt Nam có thẩm quyền xem xét.<br><br>\r\n");
      out.write("			</p>\r\n");
      out.write("      	</div>\r\n");
      out.write("      </div>\r\n");
      out.write("     </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("<!--  footer-->\r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./footer/footer.jsp", out, true);
      out.write("\r\n");
      out.write("<!-- end footer-->\r\n");
      out.write("      ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /view/client/security.jsp(3,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/view/client/assets");
      // /view/client/security.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("url");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
