/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-06-29 19:21:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import nongsan.webmvc.model.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Di/Desktop/LTWeb/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/do-an-java/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098685890000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1656093238021L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("nongsan.webmvc.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

  response.setHeader("Cache-control", "no-cache, no-store, must-revalidate");
  response.setHeader("Pragma" , "no-cache");
  response.setHeader("Expires" , "0");
  
  User u = new User();
  u = (User)session.getAttribute("account");
  if (u.getIsAdmin() == 0){
	  response.sendRedirect(request.getContextPath() + "/client/index"); 
  }
  
      out.write("\r\n");
      out.write("  <!-- Start header section -->\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./header/header.jsp", out, true);
      out.write("\r\n");
      out.write("    <div class=\"content-wrapper\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"card mt-3\">\r\n");
      out.write("          <div class=\"card-content\">\r\n");
      out.write("            <div class=\"row row-group m-0\">\r\n");
      out.write("              <div class=\"col-12 col-lg-6 col-xl-3 border-light\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <h5 class=\"text-white mb-0\">3 <span class=\"float-right\"><i class=\"fa fa-shopping-cart\"></i></span>\r\n");
      out.write("                  </h5>\r\n");
      out.write("                  <div class=\"progress my-3\" style=\"height:3px;\">\r\n");
      out.write("                    <div class=\"progress-bar\" style=\"width:55%\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <p class=\"mb-0 text-white small-font\">Đơn hàng (theo tuần)<span class=\"float-right\">+4.2% <i\r\n");
      out.write("                        class=\"zmdi zmdi-long-arrow-up\"></i></span></p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-12 col-lg-6 col-xl-3 border-light\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <h5 class=\"text-white mb-0\">230.000 <span class=\"float-right\">VNĐ</span></h5>\r\n");
      out.write("                  <div class=\"progress my-3\" style=\"height:3px;\">\r\n");
      out.write("                    <div class=\"progress-bar\" style=\"width:55%\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <p class=\"mb-0 text-white small-font\">Lợi nhuận (theo tuần)<span class=\"float-right\">+1.2% <i\r\n");
      out.write("                        class=\"zmdi zmdi-long-arrow-up\"></i></span></p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-12 col-lg-6 col-xl-3 border-light\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <h5 class=\"text-white mb-0\">25 <span class=\"float-right\"><i class=\"fa fa-eye\"></i></span></h5>\r\n");
      out.write("                  <div class=\"progress my-3\" style=\"height:3px;\">\r\n");
      out.write("                    <div class=\"progress-bar\" style=\"width:55%\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <p class=\"mb-0 text-white small-font\">Ghé trang (theo tuần)<span class=\"float-right\">+5.2% <i\r\n");
      out.write("                        class=\"zmdi zmdi-long-arrow-up\"></i></span></p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-12 col-lg-6 col-xl-3 border-light\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <h5 class=\"text-white mb-0\">3 <span class=\"float-right\"><i class=\"fa fa-envira\"></i></span></h5>\r\n");
      out.write("                  <div class=\"progress my-3\" style=\"height:3px;\">\r\n");
      out.write("                    <div class=\"progress-bar\" style=\"width:55%\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <p class=\"mb-0 text-white small-font\">Bán ra (theo tuần)<span class=\"float-right\">+2.2% <i\r\n");
      out.write("                        class=\"zmdi zmdi-long-arrow-up\"></i></span></p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-12 col-lg-4 col-xl-4\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <div class=\"card-header\">Danh mục bán chạy\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <div class=\"chart-container-2\">\r\n");
      out.write("                  <canvas id=\"chart2\"></canvas>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"table-responsive\">\r\n");
      out.write("                <table class=\"table align-items-center\">\r\n");
      out.write("                  <tbody>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td><i class=\"fa fa-circle text-white mr-2\"></i>Rau sạch</td>\r\n");
      out.write("                      <td>58.000 VNĐ</td>\r\n");
      out.write("                      <td>+55%</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td><i class=\"fa fa-circle text-light-1 mr-2\"></i>Củ quả</td>\r\n");
      out.write("                      <td>110.000 VNĐ</td>\r\n");
      out.write("                      <td>+25%</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td><i class=\"fa fa-circle text-light-2 mr-2\"></i>Hạt</td>\r\n");
      out.write("                      <td>215.500 VNĐ</td>\r\n");
      out.write("                      <td>+15%</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td><i class=\"fa fa-circle text-light-3 mr-2\"></i>Mật ong</td>\r\n");
      out.write("                      <td>310.000 VNĐ</td>\r\n");
      out.write("                      <td>+5%</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <a href=\"javaScript:void();\" class=\"back-to-top\"><i class=\"fa fa-angle-double-up\"></i> </a>\r\n");
      out.write("    <div class=\"right-sidebar\">\r\n");
      out.write("      <div class=\"switcher-icon\">\r\n");
      out.write("        <i class=\"zmdi zmdi-settings zmdi-hc-spin\"></i>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"right-sidebar-content\">\r\n");
      out.write("        <p class=\"mb-0\">Màu nền admin</p>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <ul class=\"switcher\">\r\n");
      out.write("          <li id=\"theme1\"></li>\r\n");
      out.write("          <li id=\"theme2\"></li>\r\n");
      out.write("          <li id=\"theme3\"></li>\r\n");
      out.write("          <li id=\"theme4\"></li>\r\n");
      out.write("          <li id=\"theme5\"></li>\r\n");
      out.write("          <li id=\"theme6\"></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <p class=\"mb-0\">Màu nền gradient</p>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <ul class=\"switcher\">\r\n");
      out.write("          <li id=\"theme7\"></li>\r\n");
      out.write("          <li id=\"theme8\"></li>\r\n");
      out.write("          <li id=\"theme9\"></li>\r\n");
      out.write("          <li id=\"theme10\"></li>\r\n");
      out.write("          <li id=\"theme11\"></li>\r\n");
      out.write("          <li id=\"theme12\"></li>\r\n");
      out.write("          <li id=\"theme13\"></li>\r\n");
      out.write("          <li id=\"theme14\"></li>\r\n");
      out.write("          <li id=\"theme15\"></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./footer/footer.jsp", out, true);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
